# DAY 14,15 ASSIGNMENT

# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.47072263 0.77680797 0.0851829 ]
  [0.33257966 0.57553084 0.23682783]
  [0.25427398 0.0319483  0.11956171]]

 [[0.91343403 0.80624475 0.67214857]
  [0.45378859 0.95882119 0.7973056 ]
  [0.40899547 0.75078249 0.89368272]]

 [[0.0530621  0.1885295  0.70368555]
  [0.50766216 0.44021722 0.25959104]
  [0.38232526 0.03181708 0.05472288]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
x = np.ones((3,3))
print("CHECKERBOARD PATTERN")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

CHECKERBOARD PATTERN
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [ ]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.70708945 0.30584378 0.80510422 0.1264166  0.82882761]
 [0.50096051 0.6434331  0.04861904 0.76745615 0.4126747 ]
 [0.54747752 0.69559889 0.7154304  0.72190621 0.        ]
 [0.01365115 0.25830003 0.3244647  0.62574523 1.        ]
 [0.69531734 0.26719499 0.54185389 0.2603288  0.25404097]]


# 5.  How to find common values between two arrays?

In [ ]:
array1 = np.array([0, 10, 20, 30, 40])
print("Array1: ",array1)
array2 = [20, 40, 60]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 30 40]
Array2:  [20, 40, 60]
Common values between two arrays:
[20 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("YESTERDAY:",yesterday)
today = np.datetime64('today', 'D')
print("TODAY:    ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("TOMORROW: ",tomorrow)

YESTERDAY: 2020-07-27
TODAY:     2020-07-28
TOMORROW:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [ ]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 0 1 1 1 0]
Second array:
[1 1 0 1 1 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [ ]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.38875933 0.12386001 0.75438324 0.42310077 0.17948361 0.63858903
 0.99307613 0.45417372 0.66378456 0.52173255]
Maximum value replaced by 0:
[0.38875933 0.12386001 0.75438324 0.42310077 0.17948361 0.63858903
 0.         0.45417372 0.66378456 0.52173255]


# 9. How to print all the values of an array?

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [ ]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.96908723 0.43040376 0.77744718 0.0464926  0.89178806 0.40459165
  0.25325321 0.38882455 0.96086171 0.46687295]
 [0.11958641 0.16944324 0.99927096 0.3717337  0.03569665 0.56950162
  0.78416702 0.67710643 0.45387945 0.01362699]
 [0.90169675 0.15702467 0.56273899 0.26232784 0.1861439  0.96592897
  0.12902896 0.21485525 0.01103223 0.63815817]
 [0.58419736 0.02266232 0.5669585  0.92345152 0.42094837 0.67073416
  0.35882229 0.67279418 0.26354504 0.34724548]
 [0.63617267 0.77358789 0.73079216 0.47393797 0.79302087 0.45451487
  0.59776013 0.37849759 0.68995319 0.09533788]]

Subtract the mean of each row of the said matrix:

[[ 0.41012494 -0.12855853  0.21848489 -0.51246969  0.33282577 -0.15437064
  -0.30570908 -0.17013774  0.40189942 -0.09208934]
 [-0.29981484 -0.24995801  0.57986971 -0.04766754 -0.3837046   0.15010037
   0.36476577  0.25770518  0.03447821 -0.40577426]
 [ 0.49880318 -0.24586891  0.15984541 -0.14056573 -0.21674967  0.5630354
  -0.27386461 -0.18803832 -0.39

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [ ]:
#METHOD 1
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 3. 7. 2. 1. 3. 4. 3. 4. 2.]


In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 5. 2. 2. 2. 3. 4. 1. 6. 2.]


In [ ]:
#METHOD2
np.add.at(Z, I, 1)
print(Z)

[ 5.  9.  3.  3.  3.  5.  7.  1. 11.  3.]


In [ ]:
np.add.at(Z, I, 1)
print(Z)

[ 7. 13.  4.  4.  4.  7. 10.  1. 16.  4.]


# 12.How to get the diagonal of a dot product?

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.40690942, 1.49515994, 1.35903642, 1.44939253, 0.66072863])

# 13.How to find the most frequent value in an array?

In [ ]:
x = np.random.randint(0, 10, 30)
print(x)
print("most frequent value in the array is:" ,np.bincount(x).argmax())

[9 6 8 0 7 0 4 5 3 6 2 0 3 4 9 1 9 1 6 2 8 9 2 9 7 7 4 8 3 1]
most frequent value in the array is: 9


# 14.How to get the n largest values of an array

In [ ]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 2
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[8 9]


# 15.How to create a record array from a regular array?

In [ ]:
array1 = np.array([("Elena Gilbert", 27.5, 20),("Stephan Salvatore", 156.2, 19),("Demon Salvatore", 156.2, 20)])
print("Original arrays:")
print(array1)
print("\nRecord array;")
result = np.core.records.fromarrays(array1.T,names='col1, col2, col3',formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Elena Gilbert' '27.5' '20']
 ['Stephan Salvatore' '156.2' '19']
 ['Demon Salvatore' '156.2' '20']]

Record array;
[(b'Elena Gilbert',  27.5, 20) (b'Stephan Salvatore', 156.2, 19)
 (b'Demon Salvatore', 156.2, 20)]
